### ISSUE TITLE
List files satisfying a glob

### ISSUE THREAD

**Issue by VictorDenisov** [California-QSO-Party/cabfixer#1]
As part of this story you should implement a simple command line app that lists all files in the directory that satisfy the provided glob.

$ cabfixer *.log

**Comment by tepperly** [comment]
For Linux, the shell will expand the glob before the  program sees it.

**Comment by VictorDenisov** [comment]
Right. Basically the task is to process a list of arguments as file names.

**Comment by VictorDenisov** [comment]
We decided to still treat arguments as globs because Windows command line doesn't expand globs. It will work in both environments.
