### ISSUE TITLE
Handle X-QSO lines

### ISSUE THREAD

**Issue by VictorDenisov** [California-QSO-Party/cabfixer#8]

**Comment by VictorDenisov** [comment]
@tepperly I'm wondering if X-QSO lines should be skipped altogether and not accounted while calculating the columns. What do you think?

**Comment by tepperly** [comment]
I think we should process X-QSO: lines like QSO: lines assuming that everything will be shifted 2 columns right as compared with QSO: lines. If we had a situation where W1AW has a QSO line logging a QSO with NS6T and NS6T has an X-QSO: line that matches. It could influence whether W1AW gets a NIL for that QSO line.

Tom
